---
# tasks file for openjdk8 - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ openjdk8_app_debian }}
  apt:
    name: "{{ openjdk8_app_debian }}"
    state: "{{ openjdk8_desired_state }}"
    force_apt_get: yes
    update_cache: yes
